name: Java CI

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Compile Java Program
      run: javac HelloWorld.java

    - name: Run Java Program
      run: java HelloWorld

