name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run: railway up --project ${{ secrets.SCS225_JAVA_RAILWAY_PROJECT_ID}}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

